// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApplyActionData, ApplyActionErrors, ApplyActionResponses, CreateNoteData, CreateNoteErrors, CreateNoteResponses, EditNoteByIdData, EditNoteByIdErrors, EditNoteByIdResponses, GetNoteByIdData, GetNoteByIdErrors, GetNoteByIdResponses, ListNotesData, ListNotesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Notes
 */
export const listNotes = <ThrowOnError extends boolean = false>(options?: Options<ListNotesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListNotesResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'x-temp-key',
                type: 'apiKey'
            }
        ],
        url: '/note/',
        ...options
    });
};

/**
 * Create Note
 */
export const createNote = <ThrowOnError extends boolean = false>(options: Options<CreateNoteData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateNoteResponses, CreateNoteErrors, ThrowOnError>({
        security: [
            {
                name: 'x-temp-key',
                type: 'apiKey'
            }
        ],
        url: '/note/',
        ...options
    });
};

/**
 * Get Note By Id
 */
export const getNoteById = <ThrowOnError extends boolean = false>(options: Options<GetNoteByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetNoteByIdResponses, GetNoteByIdErrors, ThrowOnError>({
        security: [
            {
                name: 'x-temp-key',
                type: 'apiKey'
            }
        ],
        url: '/note/{note_id}',
        ...options
    });
};

/**
 * Edit Note By Id
 */
export const editNoteById = <ThrowOnError extends boolean = false>(options: Options<EditNoteByIdData, ThrowOnError>) => {
    return (options.client ?? client).patch<EditNoteByIdResponses, EditNoteByIdErrors, ThrowOnError>({
        security: [
            {
                name: 'x-temp-key',
                type: 'apiKey'
            }
        ],
        url: '/note/{note_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Apply Action
 */
export const applyAction = <ThrowOnError extends boolean = false>(options: Options<ApplyActionData, ThrowOnError>) => {
    return (options.client ?? client).post<ApplyActionResponses, ApplyActionErrors, ThrowOnError>({
        security: [
            {
                name: 'x-temp-key',
                type: 'apiKey'
            }
        ],
        url: '/action/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
