// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ActionEditModel
 */
export type ActionEditModel = {
    /**
     * Note Id
     */
    note_id: string;
    /**
     * Action
     */
    action: string;
};

/**
 * ActionModel
 */
export type ActionModel = {
    /**
     * Note Action Id
     */
    note_action_id: string;
    /**
     * Note Id
     */
    note_id: string;
    /**
     * Action
     */
    action: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NoteEditModel
 */
export type NoteEditModel = {
    /**
     * Content
     */
    content: string;
};

/**
 * NoteModel
 */
export type NoteModel = {
    /**
     * Note Id
     */
    note_id: string;
    /**
     * Content
     */
    content: string;
};

/**
 * NoteViewModel
 */
export type NoteViewModel = {
    /**
     * Note Id
     */
    note_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Actions
     */
    actions: Array<ActionModel>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListNotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/note/';
};

export type ListNotesResponses = {
    /**
     * Response List Notes Note  Get
     *
     * Successful Response
     */
    200: Array<NoteModel>;
};

export type ListNotesResponse = ListNotesResponses[keyof ListNotesResponses];

export type CreateNoteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Content
         */
        content: string;
    };
    url: '/note/';
};

export type CreateNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateNoteError = CreateNoteErrors[keyof CreateNoteErrors];

export type CreateNoteResponses = {
    /**
     * Successful Response
     */
    200: NoteModel;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type GetNoteByIdData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/note/{note_id}';
};

export type GetNoteByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNoteByIdError = GetNoteByIdErrors[keyof GetNoteByIdErrors];

export type GetNoteByIdResponses = {
    /**
     * Successful Response
     */
    200: NoteViewModel;
};

export type GetNoteByIdResponse = GetNoteByIdResponses[keyof GetNoteByIdResponses];

export type EditNoteByIdData = {
    body: NoteEditModel;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/note/{note_id}';
};

export type EditNoteByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditNoteByIdError = EditNoteByIdErrors[keyof EditNoteByIdErrors];

export type EditNoteByIdResponses = {
    /**
     * Successful Response
     */
    200: NoteModel;
};

export type EditNoteByIdResponse = EditNoteByIdResponses[keyof EditNoteByIdResponses];

export type ApplyActionData = {
    body: ActionEditModel;
    path?: never;
    query?: never;
    url: '/action/';
};

export type ApplyActionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplyActionError = ApplyActionErrors[keyof ApplyActionErrors];

export type ApplyActionResponses = {
    /**
     * Successful Response
     */
    200: NoteModel;
};

export type ApplyActionResponse = ApplyActionResponses[keyof ApplyActionResponses];
