"""Add owner column

Revision ID: 645089e5533c
Revises: 7900d17102d0
Create Date: 2025-11-10 19:28:28.876915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "645089e5533c"
down_revision: Union[str, Sequence[str], None] = "7900d17102d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

note = sa.table("note", sa.column("owner", sa.Text()))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("owner", sa.Text(), nullable=True))
    op.execute(
        sa.update(note).values({"owner": "0123456789abcdef0123456789abcdef"})
    )
    op.alter_column("note", "owner", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("note", "owner")
    # ### end Alembic commands ###
