"""Add action schema

Revision ID: 7900d17102d0
Revises: ab135d355e1e
Create Date: 2025-11-01 10:19:14.012085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7900d17102d0"
down_revision: Union[str, Sequence[str], None] = "ab135d355e1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_action",
        sa.Column(
            "note_action_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.Column("action_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.note_id"],
        ),
        sa.PrimaryKeyConstraint("note_action_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("note_action")
    # ### end Alembic commands ###
